---
apiVersion: v1
kind: Namespace
metadata:
  name: trackunit
  labels:
    name: trackunit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: trackunit
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: trackunit
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: trackunit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        # https://hub.docker.com/r/kennethreitz/httpbin/tags
      - image: docker.io/kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status/200
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
      # https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints
      # proper way to spread the pods since k8s v1.19
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: httpbin
